services:
  - type: web
    name: reto-tecnico-api
    runtime: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/auth/emails
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_MS
        value: 86400000
      - key: ENCRYPTION_KEY
        sync: false
      - key: HMAC_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_CLIENT_ID
        sync: false
      - key: FACEBOOK_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://nodo404.vercel.app/